sonar.verbose=true
sonar.organization=enochdstr-mykey
sonar.projectKey=enochdstr-mykey_enochdstr
sonar.projectName=enochdstr
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
